imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services_admin.yml" }
    - { resource: "@CaramiaAdminBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    available_locales: fr
    enabled_locales: ['fr', 'en']

    upload_uri: /wp-content/uploads
    upload_dir: '%kernel.root_dir%/../web%upload_uri%'

    contact:
        phone: +33 (0)1 42 23 54 75
        linkedin: https://www.linkedin.com/company/tulipes-&-cie
        facebook: https://www.facebook.com/Tulipes-Cie-282080538471650/
        twitter: https://twitter.com/TulipesCie
        instagram: https://www.instagram.com/tulipescie/
        youtube: https://www.youtube.com/channel/UClTHeB90X7luegE6GsK3bUQ
        vimeo: https://vimeo.com/tulipesetcie

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true

ivory_ck_editor:
    plugins:
        base64image:
            path:     "/bundles/app/js/ckeditor/plugin/base64image/"
            filename: "plugin.js"

    configs:
        default:
            toolbar:
                - [ "Bold", "Italic", "Underline", "Subscript", "Superscript"]
                - [ "BulletedList"]
                - [ "Styles"]
                - [ "Link", "Unlink" ]
                - [ "iframe" ]
            stylesSet: "tulipes_ck_content:/bundles/app/js/ckeditor/js/tulipes_ck_content.js"
            contentsCss: "/bundles/app/js/ckeditor/css/index.css"
            bodyClass: "tulipes_ck_content"

        project_content:
            toolbar:
                - [ "Bold", "Italic", "Underline", "Subscript", "Superscript"]
                - [ "BulletedList"]
                - [ "Styles"]
                - [ "Link", "Unlink" ]
                - [ "base64image", "File", "Iframe"]
            stylesSet: "tulipes_ck_content:/bundles/app/js/ckeditor/js/tulipes_ck_content.js"
            contentsCss: "/bundles/app/js/ckeditor/css/styles.css"
            bodyClass: "tulipes_ck_content"
            extraPlugins: "base64image"
            enterMode: "CKEDITOR.ENTER_P"



sonata_admin:
    title_logo: /bundles/app/img/logo-tulipes-white.png
    options:
        title_mode: single_image
    extensions: 
        caramia_translation.admin.translatable:
            uses: 
                - Caramia\TranslationBundle\Traits\TranslatableEntity

caramia_translation:
    locales: %enabled_locales%

sonata_doctrine_orm_admin:
    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
            - CaramiaMediaBundle:Form:form_admin_fields.html.twig

vich_uploader:
    db_driver: orm

    mappings:
        media_item:
            uri_prefix:         '%upload_uri%'
            upload_destination: '%upload_dir%'
            inject_on_load:     true
            namer:
                service:        vich_uploader.namer_origname
                options:        { transliterate: true }
        contact_file:
            uri_prefix:         /contact_file
            upload_destination: '%kernel.root_dir%/../data/contact_file'
            inject_on_load:     true
            namer:
                service:        vich_uploader.namer_origname
                options:        { transliterate: true }

happyr_linkedin:
    app_id: '%linkedin_api_key%'
    app_secret: '%linkedin_api_secret%'
    request_format: 'json' # Default
    response_format: 'array' # Default
    http_client: 'httplug.client' # Service ID for an object implementing Http\Client\HttpClient
    http_message_factory: 'httplug.message_factory' # Service ID for an object implementing Http\Message\MessageFactory
