<?php

namespace AppBundle\Repository\Page;

/**
 * ContactPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPageRepository extends \Doctrine\ORM\EntityRepository
{
}
